### ISSUE TITLE
pbs import structure is possibly broken

### ISSUE THREAD

**Issue by averagehat** [VDBWRAIR/pbs#4]
For example, https://github.com/VDBWRAIR/pbs/blob/4d2a08d55a39a256f8acb715cb7f6726f71ef58c/pbs/__init__.template.py

tests will run like PYTHONPATH=PYTHONPATH:$PWD/pbs:$PWD nosetests tests 
but might fail otherwise.

**Comment by necrolyte2** [comment]
I think that #10 might fix this since it can install now

**Comment by averagehat** [comment]
Confirmed, the scripts seem to work, although

``` python
(.pbs)-bash-4.1$ pstat 1561
Traceback (most recent call last):
  File "/media/VD_Research/People/michael.panciera/.pbs/bin/pstat", line 9, in <module>
    load_entry_point('pbs===VERSION-ID.-git.sha.COMMIT-ID-dev', 'console_scripts', 'pstat')()
  File "/media/VD_Research/People/michael.panciera/pbs/pbs/pstat.py", line 295, in main
    print_jobs(args,db)
  File "/media/VD_Research/People/michael.panciera/pbs/pbs/pstat.py", line 145, in print_jobs
    jobid = select_job(args)
TypeError: select_job() takes exactly 2 arguments (1 given)
```

simple $ qstat did work though

_Edit:_ it looks like relative imports from test_custom.py might be broken still
